### ISSUE TITLE
unsupported operant Timestamp and NoneType

### ISSUE THREAD

**Issue by zyxelenator** [2018kguo/RobinhoodBot#15]
After buy scan:
Traceback (most recent call last):
  File "main.py", line 271, in <module>
    scan_stocks()
  File "main.py", line 259, in scan_stocks
    cross = golden_cross(symbol, n1=50, n2=200, days=10, direction="above")
  File "main.py", line 166, in golden_cross
    if(direction == "above" and not five_year_check(stockTicker)):
  File "main.py", line 138, in five_year_check
    if ((pd.Timestamp("now") - pd.to_datetime(list_date)) < pd.Timedelta("5 Y")):
TypeError: unsupported operand type(s) for -: 'Timestamp' and 'NoneType'

**Comment by Jroc561** [comment]
I never had this error until one of the stocks on my watchlist triggered it, I then tried a couple things and couldnt get a fix for it. So I ended up removing the five year check in total.

**Comment by razo559** [comment]
> I never had this error until one of the stocks on my watchlist triggered it, I then tried a couple things and couldnt get a fix for it. So I ended up removing the five year check in total.

How do you remove the 5 year check?

**Comment by Jeraz** [comment]
I had to change pd.Timedelta("5 Y") to pd.Timedelta(365*5, unit='D') to make it work with the new Panda library. Not sure if that helps.
