### ISSUE TITLE
    scan_stocks() not working pls help?

### ISSUE THREAD

**Issue by markmark1** [2018kguo/RobinhoodBot#3]
----- Scanning portfolio for stocks to sell -----

----- Scanning watchlist for stocks to buy -----

Traceback (most recent call last):
  File "main.py", line 259, in <module>
    scan_stocks()
  File "main.py", line 248, in scan_stocks
    cross = golden_cross(symbol, n1=50, n2=200, days=10, direction="above")
  File "main.py", line 159, in golden_cross
    if(direction == "above" and not five_year_check(stockTicker)):
  File "main.py", line 131, in five_year_check
    if ((pd.Timestamp("now") - pd.to_datetime(list_date)) < pd.Timedelta("5 Y")):
TypeError: unsupported operand type(s) for -: 'Timestamp' and 'NoneType'

**Comment by txavier** [comment]
I believe this issue is due to a new version of robin_stocks.  I have corrected this in my fork.
