### ISSUE TITLE
bollinger_mavg Error

### ISSUE THREAD

**Issue by CruelPlanet** [2018kguo/RobinhoodBot#9]
Has anyone else been getting this error as of a few days ago? I modified the program slightly to run continuously but even redownloading it and not changing any of the code seems to generate this error now and I was hoping someone else has encountered this and knows a fix.

Traceback (most recent call last):
  File "C:\Users\johnz\Downloads\RobinhoodBot-master\RobinhoodBot-master\robinhoodbot\main.py", line 258, in <module>
    scan_stocks()
  File "C:\Users\johnz\Downloads\RobinhoodBot-master\RobinhoodBot-master\robinhoodbot\main.py", line 248, in scan_stocks
    cross = golden_cross(symbol, n1=50, n2=200, days=10, direction="above")
  File "C:\Users\johnz\Downloads\RobinhoodBot-master\RobinhoodBot-master\robinhoodbot\main.py", line 170, in golden_cross
    sma1 = bollinger_mavg(price, n=int(n1), fillna=False)
NameError: name 'bollinger_mavg' is not defined

**Comment by CruelPlanet** [comment]
Never mind I'm an idiot as soon as I posted this I noticed someone else had the same error and it was already solved.
